### ISSUE TITLE
Install yarn

### ISSUE THREAD

**Issue by yahonda** [yahonda/multipass-rails-dev-box#15]
### Steps to reproduce

- At multipass host
```
multipass launch 24.04 --cpus 4 --disk 20G --memory 8G --name rails-dev-box --cloud-init ./cloud-init.yaml --timeout 1200
multipass shell rails-dev-box
```

- At multipass guest
```
git clone https://github.com/rails/rails
cd rails
bundle update --bundler
bundle install
cd activestorage
bin/test test/javascript_package_test.rb
```

### Expected behavior
All of tests should pass.

### Actual behavior
It gets the following error because the yarn is not installed.

```
Error:
JavascriptPackageTest#test_compiled_code_is_in_sync_with_source_code:
Errno::ENOENT: No such file or directory - yarn
    test/javascript_package_test.rb:15:in `system'
    test/javascript_package_test.rb:15:in `block in test_compiled_code_is_in_sync_with_source_code'
    /home/ubuntu/rails/activesupport/lib/active_support/testing/assertions.rb:49:in `assert_nothing_raised'
    /home/ubuntu/rails/activesupport/lib/active_support/testing/assertions.rb:287:in `_assert_nothing_raised_or_warn'
    /home/ubuntu/rails/activesupport/lib/active_support/testing/assertions.rb:256:in `assert_no_changes'
    test/javascript_package_test.rb:14:in `test_compiled_code_is_in_sync_with_source_code'


bin/rails test /home/ubuntu/rails/activestorage/test/javascript_package_test.rb:6
```

**Comment by yahonda** [comment]
Fixed by https://github.com/yahonda/multipass-rails-dev-box/pull/18
