### ISSUE TITLE
Address Selenium error

### ISSUE THREAD

**Issue by yahonda** [yahonda/multipass-rails-dev-box#17]
### Steps to reproduce

- At multipass host
```
multipass launch 24.04 --cpus 4 --disk 20G --memory 8G --name rails-dev-box --cloud-init ./cloud-init.yaml --timeout 1200
multipass shell rails-dev-box
```

- At multipass guest
```
git clone https://github.com/rails/rails
cd rails
bundle update --bundler
bundle install
cd actionpack
bin/test
```

### Expected behavior
It should pass.

### Actual behavior

```
$ bin/test
2024-08-15 14:42:06 INFO Selenium [:logger_info] Details on how to use and modify Selenium logger:
  https://selenium.dev/documentation/webdriver/troubleshooting/logging

2024-08-15 14:42:06 ERROR Selenium Exception occurred: Unsuccessful command executed: ["/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/bin/linux/selenium-manager", "--browser", "chrome", "--language-binding", "ruby", "--output", "json"] - Code 2
{}
/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/bin/linux/selenium-manager: 1: Syntax error: "(" unexpected

2024-08-15 14:42:06 ERROR Selenium Backtrace:
	/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/lib/selenium/webdriver/common/selenium_manager.rb:81:in `run'
	/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/lib/selenium/webdriver/common/selenium_manager.rb:44:in `binary_paths'
	/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/lib/selenium/webdriver/common/driver_finder.rb:58:in `paths'
	/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/lib/selenium/webdriver/common/driver_finder.rb:39:in `driver_path'
	/home/ubuntu/rails/actionpack/lib/action_dispatch/system_testing/browser.rb:77:in `resolve_driver_path'
	/home/ubuntu/rails/actionpack/lib/action_dispatch/system_testing/browser.rb:45:in `preload'
	/home/ubuntu/rails/actionpack/lib/action_dispatch/system_testing/driver.rb:21:in `initialize'
	/home/ubuntu/rails/actionpack/lib/action_dispatch/system_test_case.rb:161:in `new'
	/home/ubuntu/rails/actionpack/lib/action_dispatch/system_test_case.rb:161:in `driven_by'
	/home/ubuntu/rails/actionpack/test/abstract_unit.rb:521:in `<class:DrivenBySeleniumWithChrome>'
	/home/ubuntu/rails/actionpack/test/abstract_unit.rb:520:in `<top (required)>'
	/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	/home/ubuntu/rails/actionpack/test/abstract/callbacks_test.rb:3:in `<top (required)>'
	/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	/home/ubuntu/rails/railties/lib/rails/test_unit/runner.rb:62:in `block in load_tests'
	/home/ubuntu/rails/railties/lib/rails/test_unit/runner.rb:60:in `each'
	/home/ubuntu/rails/railties/lib/rails/test_unit/runner.rb:60:in `load_tests'
	/home/ubuntu/rails/railties/lib/rails/test_unit/runner.rb:52:in `run'
	/home/ubuntu/rails/tools/test.rb:18:in `<top (required)>'
	bin/test:5:in `require_relative'
	bin/test:5:in `<main>'
/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/lib/selenium/webdriver/common/driver_finder.rb:75:in `rescue in paths': Unable to obtain chromedriver; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location (Selenium::WebDriver::Error::NoSuchDriverError)
	from /home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/lib/selenium/webdriver/common/driver_finder.rb:49:in `paths'
	from /home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/lib/selenium/webdriver/common/driver_finder.rb:39:in `driver_path'
	from /home/ubuntu/rails/actionpack/lib/action_dispatch/system_testing/browser.rb:77:in `resolve_driver_path'
	from /home/ubuntu/rails/actionpack/lib/action_dispatch/system_testing/browser.rb:45:in `preload'
	from /home/ubuntu/rails/actionpack/lib/action_dispatch/system_testing/driver.rb:21:in `initialize'
	from /home/ubuntu/rails/actionpack/lib/action_dispatch/system_test_case.rb:161:in `new'
	from /home/ubuntu/rails/actionpack/lib/action_dispatch/system_test_case.rb:161:in `driven_by'
	from /home/ubuntu/rails/actionpack/test/abstract_unit.rb:521:in `<class:DrivenBySeleniumWithChrome>'
	from /home/ubuntu/rails/actionpack/test/abstract_unit.rb:520:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /home/ubuntu/rails/actionpack/test/abstract/callbacks_test.rb:3:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /home/ubuntu/rails/railties/lib/rails/test_unit/runner.rb:62:in `block in load_tests'
	from /home/ubuntu/rails/railties/lib/rails/test_unit/runner.rb:60:in `each'
	from /home/ubuntu/rails/railties/lib/rails/test_unit/runner.rb:60:in `load_tests'
	from /home/ubuntu/rails/railties/lib/rails/test_unit/runner.rb:52:in `run'
	from /home/ubuntu/rails/tools/test.rb:18:in `<top (required)>'
	from bin/test:5:in `require_relative'
	from bin/test:5:in `<main>'
/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/lib/selenium/webdriver/common/selenium_manager.rb:81:in `run': Unsuccessful command executed: ["/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/bin/linux/selenium-manager", "--browser", "chrome", "--language-binding", "ruby", "--output", "json"] - Code 2 (Selenium::WebDriver::Error::WebDriverError)
{}
/home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/bin/linux/selenium-manager: 1: Syntax error: "(" unexpected

	from /home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/lib/selenium/webdriver/common/selenium_manager.rb:44:in `binary_paths'
	from /home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/lib/selenium/webdriver/common/driver_finder.rb:58:in `paths'
	from /home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/selenium-webdriver-4.22.0/lib/selenium/webdriver/common/driver_finder.rb:39:in `driver_path'
	from /home/ubuntu/rails/actionpack/lib/action_dispatch/system_testing/browser.rb:77:in `resolve_driver_path'
	from /home/ubuntu/rails/actionpack/lib/action_dispatch/system_testing/browser.rb:45:in `preload'
	from /home/ubuntu/rails/actionpack/lib/action_dispatch/system_testing/driver.rb:21:in `initialize'
	from /home/ubuntu/rails/actionpack/lib/action_dispatch/system_test_case.rb:161:in `new'
	from /home/ubuntu/rails/actionpack/lib/action_dispatch/system_test_case.rb:161:in `driven_by'
	from /home/ubuntu/rails/actionpack/test/abstract_unit.rb:521:in `<class:DrivenBySeleniumWithChrome>'
	from /home/ubuntu/rails/actionpack/test/abstract_unit.rb:520:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /home/ubuntu/rails/actionpack/test/abstract/callbacks_test.rb:3:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /home/ubuntu/.rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /home/ubuntu/rails/railties/lib/rails/test_unit/runner.rb:62:in `block in load_tests'
	from /home/ubuntu/rails/railties/lib/rails/test_unit/runner.rb:60:in `each'
	from /home/ubuntu/rails/railties/lib/rails/test_unit/runner.rb:60:in `load_tests'
	from /home/ubuntu/rails/railties/lib/rails/test_unit/runner.rb:52:in `run'
	from /home/ubuntu/rails/tools/test.rb:18:in `<top (required)>'
	from bin/test:5:in `require_relative'
	from bin/test:5:in `<main>'
$
```

**Comment by yahonda** [comment]
Fixed by https://github.com/yahonda/multipass-rails-dev-box/pull/19
